/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconBookmarkEmpty: typeof import('./src/components/icons/IconBookmarkEmpty.vue')['default']
    IconBookmarkFull: typeof import('./src/components/icons/IconBookmarkFull.vue')['default']
    IconCategoryMovie: typeof import('./src/components/icons/IconCategoryMovie.vue')['default']
    IconCategoryTV: typeof import('./src/components/icons/IconCategoryTV.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconNavBookmark: typeof import('./src/components/icons/IconNavBookmark.vue')['default']
    IconNavHome: typeof import('./src/components/icons/IconNavHome.vue')['default']
    IconNavMovies: typeof import('./src/components/icons/IconNavMovies.vue')['default']
    IconNavTVSeries: typeof import('./src/components/icons/IconNavTVSeries.vue')['default']
    IconPlay: typeof import('./src/components/icons/IconPlay.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MenuHeader: typeof import('./src/components/shared/MenuHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
